# Generated by Django 2.1.2 on 2018-10-21 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klass', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alt_Klass_Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('slot_length', models.IntegerField()),
                ('num_slots', models.IntegerField()),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.Klass', verbose_name='Class')),
            ],
            options={
                'verbose_name': 'Alternate Class Day',
            },
        ),
        migrations.CreateModel(
            name='Default_School_Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('slot_length', models.IntegerField()),
                ('num_slots', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
            ],
            options={
                'verbose_name': 'Default Day',
            },
        ),
    ]
